baseURL = 'yunus.tuzun.interise.space/'
languageCode = 'en-us'
title = 'Yunus Tuzun | Personal Website'
theme="archie" 
copyright = "Â© Yunus Tuzun"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
favicon = "static/favicon.png"
og_image = "static/og-image.png"
# mode = "auto"
mode = "toggle"
useCDN = true
subtitle = ""
description = "Tuzun Yunus | Personal Website"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/yunus-tuzun"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4